export const GET_BOOKS="GET_BOOKS"
export const GET_MOVIES="GET_MOVIES"
export const GET_CHARACTER="GET_CHARACTER"
export const GET_QOUTES="GET_QOUTES"
export const SET_CHARACTER_FIELDS = 'SET_CHARACTER_FIELDS';
export const SET_CHARACTER_FILTERS = 'SET_CHARACTER_FILTERS';
export const SET_MOVIES_FIELDS = 'SET_MOVIES_FIELDS';
export const SET_MOVIES_FILTERS = 'SET_MOVIES_FILTERS';